/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lampa.alfabattle.second.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UserPaymentStats
 */
@JsonPropertyOrder({
        UserPaymentStats.JSON_PROPERTY_MAX_AMOUNT_CATEGORY_ID,
        UserPaymentStats.JSON_PROPERTY_MIN_AMOUNT_CATEGORY_ID,
        UserPaymentStats.JSON_PROPERTY_OFTEN_CATEGORY_ID,
        UserPaymentStats.JSON_PROPERTY_RARE_CATEGORY_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-27T15:06:47.007876100+03:00[Europe/Moscow]")
public class UserPaymentStats {
    public static final String JSON_PROPERTY_MAX_AMOUNT_CATEGORY_ID = "maxAmountCategoryId";
    private Integer maxAmountCategoryId;

    public static final String JSON_PROPERTY_MIN_AMOUNT_CATEGORY_ID = "minAmountCategoryId";
    private Integer minAmountCategoryId;

    public static final String JSON_PROPERTY_OFTEN_CATEGORY_ID = "oftenCategoryId";
    private Integer oftenCategoryId;

    public static final String JSON_PROPERTY_RARE_CATEGORY_ID = "rareCategoryId";
    private Integer rareCategoryId;


    public UserPaymentStats maxAmountCategoryId(Integer maxAmountCategoryId) {

        this.maxAmountCategoryId = maxAmountCategoryId;
        return this;
    }

    /**
     * Get maxAmountCategoryId
     *
     * @return maxAmountCategoryId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_MAX_AMOUNT_CATEGORY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMaxAmountCategoryId() {
        return maxAmountCategoryId;
    }


    public void setMaxAmountCategoryId(Integer maxAmountCategoryId) {
        this.maxAmountCategoryId = maxAmountCategoryId;
    }


    public UserPaymentStats minAmountCategoryId(Integer minAmountCategoryId) {

        this.minAmountCategoryId = minAmountCategoryId;
        return this;
    }

    /**
     * Get minAmountCategoryId
     *
     * @return minAmountCategoryId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_MIN_AMOUNT_CATEGORY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMinAmountCategoryId() {
        return minAmountCategoryId;
    }


    public void setMinAmountCategoryId(Integer minAmountCategoryId) {
        this.minAmountCategoryId = minAmountCategoryId;
    }


    public UserPaymentStats oftenCategoryId(Integer oftenCategoryId) {

        this.oftenCategoryId = oftenCategoryId;
        return this;
    }

    /**
     * Get oftenCategoryId
     *
     * @return oftenCategoryId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_OFTEN_CATEGORY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getOftenCategoryId() {
        return oftenCategoryId;
    }


    public void setOftenCategoryId(Integer oftenCategoryId) {
        this.oftenCategoryId = oftenCategoryId;
    }


    public UserPaymentStats rareCategoryId(Integer rareCategoryId) {

        this.rareCategoryId = rareCategoryId;
        return this;
    }

    /**
     * Get rareCategoryId
     *
     * @return rareCategoryId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_RARE_CATEGORY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getRareCategoryId() {
        return rareCategoryId;
    }


    public void setRareCategoryId(Integer rareCategoryId) {
        this.rareCategoryId = rareCategoryId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserPaymentStats userPaymentStats = (UserPaymentStats) o;
        return Objects.equals(this.maxAmountCategoryId, userPaymentStats.maxAmountCategoryId) &&
                Objects.equals(this.minAmountCategoryId, userPaymentStats.minAmountCategoryId) &&
                Objects.equals(this.oftenCategoryId, userPaymentStats.oftenCategoryId) &&
                Objects.equals(this.rareCategoryId, userPaymentStats.rareCategoryId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(maxAmountCategoryId, minAmountCategoryId, oftenCategoryId, rareCategoryId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserPaymentStats {\n");
        sb.append("    maxAmountCategoryId: ").append(toIndentedString(maxAmountCategoryId)).append("\n");
        sb.append("    minAmountCategoryId: ").append(toIndentedString(minAmountCategoryId)).append("\n");
        sb.append("    oftenCategoryId: ").append(toIndentedString(oftenCategoryId)).append("\n");
        sb.append("    rareCategoryId: ").append(toIndentedString(rareCategoryId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

