/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lampa.alfabattle.second.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * UserPaymentAnalytic
 */
@JsonPropertyOrder({
        UserPaymentAnalytic.JSON_PROPERTY_ANALYTIC_INFO,
        UserPaymentAnalytic.JSON_PROPERTY_TOTAL_SUM,
        UserPaymentAnalytic.JSON_PROPERTY_USER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-27T15:06:47.007876100+03:00[Europe/Moscow]")
public class UserPaymentAnalytic {
    public static final String JSON_PROPERTY_ANALYTIC_INFO = "analyticInfo";
    private Map<String, PaymentCategoryInfo> analyticInfo = null;

    public static final String JSON_PROPERTY_TOTAL_SUM = "totalSum";
    private BigDecimal totalSum;

    public static final String JSON_PROPERTY_USER_ID = "userId";
    private String userId;


    public UserPaymentAnalytic analyticInfo(Map<String, PaymentCategoryInfo> analyticInfo) {

        this.analyticInfo = analyticInfo;
        return this;
    }

    public UserPaymentAnalytic putAnalyticInfoItem(String key, PaymentCategoryInfo analyticInfoItem) {
        if (this.analyticInfo == null) {
            this.analyticInfo = new HashMap<String, PaymentCategoryInfo>();
        }
        this.analyticInfo.put(key, analyticInfoItem);
        return this;
    }

    /**
     * Get analyticInfo
     *
     * @return analyticInfo
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ANALYTIC_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, PaymentCategoryInfo> getAnalyticInfo() {
        return analyticInfo;
    }


    public void setAnalyticInfo(Map<String, PaymentCategoryInfo> analyticInfo) {
        this.analyticInfo = analyticInfo;
    }


    public UserPaymentAnalytic totalSum(BigDecimal totalSum) {

        this.totalSum = totalSum;
        return this;
    }

    /**
     * Get totalSum
     *
     * @return totalSum
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TOTAL_SUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getTotalSum() {
        return totalSum;
    }


    public void setTotalSum(BigDecimal totalSum) {
        this.totalSum = totalSum;
    }


    public UserPaymentAnalytic userId(String userId) {

        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_USER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUserId() {
        return userId;
    }


    public void setUserId(String userId) {
        this.userId = userId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserPaymentAnalytic userPaymentAnalytic = (UserPaymentAnalytic) o;
        return Objects.equals(this.analyticInfo, userPaymentAnalytic.analyticInfo) &&
                Objects.equals(this.totalSum, userPaymentAnalytic.totalSum) &&
                Objects.equals(this.userId, userPaymentAnalytic.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(analyticInfo, totalSum, userId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserPaymentAnalytic {\n");
        sb.append("    analyticInfo: ").append(toIndentedString(analyticInfo)).append("\n");
        sb.append("    totalSum: ").append(toIndentedString(totalSum)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

