/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lampa.alfabattle.second.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * UserTemplate
 */
@JsonPropertyOrder({
        UserTemplate.JSON_PROPERTY_AMOUNT,
        UserTemplate.JSON_PROPERTY_CATEGORY_ID,
        UserTemplate.JSON_PROPERTY_RECIPIENT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-27T15:06:47.007876100+03:00[Europe/Moscow]")
public class UserTemplate {
    public static final String JSON_PROPERTY_AMOUNT = "amount";
    private BigDecimal amount;

    public static final String JSON_PROPERTY_CATEGORY_ID = "categoryId";
    private Integer categoryId;

    public static final String JSON_PROPERTY_RECIPIENT_ID = "recipientId";
    private String recipientId;


    public UserTemplate amount(BigDecimal amount) {

        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_AMOUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getAmount() {
        return amount;
    }


    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }


    public UserTemplate categoryId(Integer categoryId) {

        this.categoryId = categoryId;
        return this;
    }

    /**
     * Get categoryId
     *
     * @return categoryId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_CATEGORY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getCategoryId() {
        return categoryId;
    }


    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }


    public UserTemplate recipientId(String recipientId) {

        this.recipientId = recipientId;
        return this;
    }

    /**
     * Get recipientId
     *
     * @return recipientId
     **/
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_RECIPIENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRecipientId() {
        return recipientId;
    }


    public void setRecipientId(String recipientId) {
        this.recipientId = recipientId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserTemplate userTemplate = (UserTemplate) o;
        return Objects.equals(this.amount, userTemplate.amount) &&
                Objects.equals(this.categoryId, userTemplate.categoryId) &&
                Objects.equals(this.recipientId, userTemplate.recipientId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(amount, categoryId, recipientId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserTemplate {\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
        sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

